### ISSUE TITLE
Upload directory: undefined

### ISSUE THREAD

**Issue by foxit224** [DumbWareio/DumbDrop#59]
**Describe the bug**
Hi, I am currently not able to use Dumbdrop. I feel I must be doing something wrong but can't pick it. I receive the following log error response:

> dumbdrop-1  | [INFO] 2025-05-24T16:25:48.477Z - Server running at http://XXXXXXXX.com
> dumbdrop-1  | [INFO] 2025-05-24T16:25:48.478Z - Upload directory: undefined

The last line error above also comes with the following issue upon opening the app via a local ip address:

![Image](https://github.com/user-attachments/assets/305685ef-e855-4434-bbf6-c60d9ae7cdd5)

**To Reproduce**
1. I load the docker-compose.yml config file:

```
Services:
  dumbdrop:
    image: dumbwareio/dumbdrop:latest
    ports:
      - 3000:3000
    volumes:
      - /path/to/downloads/dumbdrop_uploads:/app/uploads
    environment:
      UPLOAD_DIR: /app/uploads
      DUMBDROP_TITLE: DumbDrop
      MAX_FILE_SIZE: 1024
      DUMBDROP_PIN: 123456
      AUTO_UPLOAD: false
      BASE_URL: http://mydomain.com/

```
3. I deploy the app
4. I see the "Upload directory: undefined" error
5. I attempt to access the app only to find there is the "Error checking password" issue.

**Expected behavior**
I expect the app just to run. I can't see how my volume and environmental variables are in error.

**Desktop (please complete the following information):**
 - OS:: Portainer
 - Browser: Brave

Thank you for building this app and appreciate any help you can offer!
