### ISSUE TITLE
Uploaded files not listed in UI, although present in /app/uploads

### ISSUE THREAD

**Issue by jk779** [DumbWareio/DumbDrop#65]
Hi, 

I’m running Dumbdrop using Coolify and the compose.yml from the official README. Uploading works without any issues — all chunked POSTs return 200 OK.

However, after the upload completes, no files appear in the UI.
Despite that, the uploaded files do show up correctly in /app/uploads inside the container and on the host system, so volume mounting seems to be working properly.

My compose.yml:

```yml
services:
  dumbdrop:
    image: 'dumbwareio/dumbdrop:latest'
    volumes:
      - '/root/docker/dumbdrop/local_uploads:/app/uploads'
    environment:
      DUMBDROP_TITLE: ddrop-eu2
      MAX_FILE_SIZE: 10240
      DUMBDROP_PIN: 168900
      AUTO_UPLOAD: false
      BASE_URL: 'https://d-eu2.example.com'
      UPLOAD_DIR: /app/uploads
      DEBUG: true
```

Any ideas?
Thanks in advance for any pointers!
